project:
  type: website
  output-dir: docs

website:
  title: "Noory Okthariza"
  site-url: "https://noory-okthariza.github.io"

  navbar:
    background: "#003355"
    right:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: cv.qmd
        text: CV
      - href: data.qmd
        text: Data
      - href: blog/index.qmd
        text: Blog

format:
  html:
    theme: flatly
    toc: false
    css: styles.css
    page-layout: article
    grid:
      body-width: 800px