---
title: "Publications"
---

• 2025. *Indonesia election archive: Institutions, candidates and results*. (With Khoirunnisa Agustyati, Heroik Pratama, [Johanna Birnir](https://johannabirnir.com/), Henry Overos, Iqbal Kholidin, Fadli Ramadhanil, and Amalinda Savirani). [Scientific Data](https://www.nature.com/articles/s41597-025-05746-7), Volume 12: 1397.

• 2025. *The patriarchy in the parties: Voter preferences vs. women's list placement in the 2024 legislative election in Indonesia.* (With [Johanna Birnir](https://johannabirnir.com/), Khoirunnisa Agustyati, and Heroik Pratama). [Electoral Studies](https://www.sciencedirect.com/science/article/pii/S0261379425000447), Volume 95, 102938.

• 2024. *Islamic political alignment in Indonesia: Does it truly hold?*. [Asia Policy](https://muse.jhu.edu/issue/52523), 19 (2), 213-217.

------------------------------------------------------------------------

<div style="margin-top:8px;"></div>

### Before Graduate School

• 2023. *Electoral rules effect: Explaining party system stability in democratic Indonesia.*\
In Julio C. Teehankee and Christian Echle (Eds.), [*Rethinking Parties in Democratizing Asia*](https://www.taylorfrancis.com/chapters/oa-edit/10.4324/9781003324478-5/electoral-rules-effect-noory-okthariza), pp. 102–126. Routledge.

• 2022. *Between the internal struggle and electoral rules effect: The challenges of political Islam in a democratic Indonesia.*\
In Brendan Howe (Ed.), [*Society and Democracy in South Korea and Indonesia*](https://link.springer.com/chapter/10.1007/978-3-031-06267-4_3), pp. 39–59. Palgrave Macmillan.

• 2022. *Explaining party system fragmentation at district-level in Indonesia.* [Asian Journal of Comparative Politics](https://journals.sagepub.com/doi/abs/10.1177/20578911221094090), 7(4), 1008–1024.

<br><br> <!-- adds space between sections -->

## Working Papers

• Will be updated soon
