---
title: "Tahun Ketiga"
author: ""
date: "2026-07-23"
categories:
  - PhD
  - Indonesia
---

Kuliah tahun ketiga saya selesai Mei lalu. Sekarang masuk libur summer. Sebenarnya tidak bisa dibilang libur juga karena banyak urusan riset yang harus dikerjakan. Tapi summer ini saya berkesempatan balik lagi ke Indo. Tujuan utamanya tentu untuk mengumpulkan data, plus bonusnya ketemu dengan teman-teman lama. 

Sedikit update, semester kemarin adalah semester terakhir saya ambil mata kuliah. Jadi Fall semester nanti dan seterusnya bisa riang-gembira mengerjakan riset tanpa dibebani tugas-tugas di kelas. Saya lumayan banyak ambil mata kuliah. Total selama enam semester, saya ambil enam belas mata kuliah plus satu mata kuliah reading yang cukup ketemu profesor per dua minggu. 

Semester terakhir ini mata kuliah yang saya ambil seru-seru: game theory dan prospectus. Belajar game theory buat saya seperti belajar bahasa baru. Ibaratnya seperti belajar mengerti kata-kata asing, grammar dan hubungan sintaksis supaya bisa ketemu logika dan makna yang valid. Walau cukup kesulitan, menurut saya mata kuliah ini bagus diambil mahasiswa tingkat lanjut, terutama yang ingin - seperti saya - mengonstruksi sebuah teori yang koheren. 

Mata kuliah kedua, prospectus, agak unik. Ini mata kuliah yang ditujukan untuk membuat draft proposal disertasi. Hampir setiap minggu mahasiswa dapat giliran presentasi. Formatnya kelasnya seminar, tapi tidak ada bacaan kecuali membaca draft part per part proposal teman-teman di kelas - yang kemudian akan membaca tulisan tersebut dengan sangat attentive. Urutan presentasinya mengikuti format proposal: mulai dari latar belakang dan formulasi pertanyaan penelitian, teori dan hipotesis, strategi empiris, sampai validitas data. Jadi bisa dipastikan hampir setiap minggu setiap mahasiswa kebanjiran kritik dan masukan. Tapi senangnya semua dilakukan dengan semangat kolegial.  

Walau draft proposal sudah ada, tapi saya belum bisa mulai secara formal menulis disertasi. Ujian kompre sudah selesai. Tapi saya masih harus menyelesaikan dua paper dan ujian proposal sebelum menyandang status 'kandidat doktor'. Ritus kuliah PhD di Amerika memang pelan dan mesti dilalui dengan sabar. Idealnya setiap mahasiswa bisa lulus dalam 5 tahun. Tapi bukan hal aneh ada mahasiswa baru selesai dalam 6-7 tahun bahkan lebih. 

Karena tidak ada lagi kuliah, Fall nanti saya harus (bisa) kebut menulis dua paper. Satu paper sudah dan sedang saya kerjakan sejak awal summer ini, dan yang satu lagi harusnya bisa dimulai awal Fall. Saya bilang 'harusnya' karena paper kedua ini menunggu survei nasional yang rencananya akan dilakukan kolega di CSIS Agustus/September ini. Semoga semua berjalan sesuai rencana. Jadi akhir Fall nanti, atau selambat-lambatnya awal tahun depan, saya bisa ikut ujian proposal. 